# Generated by Django 4.0.2 on 2022-02-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(max_length=20)),
                ('bname', models.CharField(max_length=100)),
                ('bauthor', models.CharField(max_length=60)),
                ('bstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
