# Generated by Django 4.0.2 on 2022-02-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='email',
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
